[project]
name = 'Digital-Public-Health-Clinic-Appointment-Reminders'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.cancellation-processing]
path = 'contracts/cancellation-processing.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
